### ISSUE TITLE
FileNotFoundError: No such file or directory: '/C.feature.pkl.gz'

### ISSUE THREAD

**Issue by addsg** [dptech-corp/Uni-Fold#133]
When I inference on a fasta file, I met some errors

>  Traceback (most recent call last):
[312]   File "/zhangyudi/Uni-Fold/unifold/homo_search.py", line 313, in <module>
[313]     app.run(main)
[314]   File "/opt/anaconda3/envs/unifold/lib/python3.10/site-packages/absl/app.py", line 308, in run
[315]     _run_main(main, args)
[316]   File "/opt/anaconda3/envs/unifold/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
[317]     sys.exit(main(argv))
[318]   File "/zhangyudi/Uni-Fold/unifold/homo_search.py", line 291, in main
[319]     generate_pkl_features(
[320]   File "/zhangyudi/Uni-Fold/unifold/homo_search.py", line 177, in generate_pkl_features
[321]     feature_dict = data_pipeline.process(
[322]   File "/zhangyudi/Uni-Fold/unifold/msa/pipeline.py", line 187, in process
[323]     msa_for_templates = parsers.deduplicate_stockholm_msa(msa_for_templates)
[324]   File "/zhangyudi/Uni-Fold/unifold/msa/parsers.py", line 364, in deduplicate_stockholm_msa
[325]     query_align = next(iter(sequence_dict.values()))
[326] StopIteration
[327] Starting prediction...
[328] start to load params multimer.unifold.pt
[329] start to predict T1187
[330] Traceback (most recent call last):
[331]   File "/zhangyudi/Uni-Fold/unifold/inference.py", line 266, in <module>
[332]     main(args)
[333]   File "/zhangyudi/Uni-Fold/unifold/inference.py", line 118, in main
[334]     batch = load_feature_for_one_target(
[335]   File "/zhangyudi/Uni-Fold/unifold/inference.py", line 61, in load_feature_for_one_target
[336]     batch, _ = load_and_process(
[337]   File "/zhangyudi/Uni-Fold/unifold/dataset.py", line 233, in load_and_process
[338]     features, labels = load(**load_kwargs, is_monomer=is_monomer)
[339]   File "/zhangyudi/Uni-Fold/unifold/dataset.py", line 129, in load
[340]     all_chain_features = [
[341]   File "/zhangyudi/Uni-Fold/unifold/dataset.py", line 130, in <listcomp>
[342]     load_single_feature(s, monomer_feature_dir, uniprot_msa_dir, is_monomer)
[343]   File "/zhangyudi/Uni-Fold/unifold/data/utils.py", line 33, in wrapper
[344]     return copy_lib.copy(cached_func(*args, **kwargs))
[345]   File "/zhangyudi/Uni-Fold/unifold/dataset.py", line 72, in load_single_feature
[346]     monomer_feature = utils.load_pickle(
[347]   File "/zhangyudi/Uni-Fold/unifold/data/utils.py", line 33, in wrapper
[348]     return copy_lib.copy(cached_func(*args, **kwargs))
[349]   File "/zhangyudi/Uni-Fold/unifold/data/utils.py", line 67, in load_pickle
[350]     ret = load(path)
[351]   File "/zhangyudi/Uni-Fold/unifold/data/utils.py", line 64, in load
[352]     with open_fn(path, "rb") as f:
[353]   File "/opt/anaconda3/envs/unifold/lib/python3.10/gzip.py", line 58, in open
[354]     binary_file = GzipFile(filename, gz_mode, compresslevel)
[355]   File "/opt/anaconda3/envs/unifold/lib/python3.10/gzip.py", line 174, in __init__
[356]     fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
[357] FileNotFoundError: [Errno 2] No such file or directory: '/zhangyudi/Uni-Fold/result_casp/T1187/T1187/C.feature.pkl.gz'

I had inferenced a lot of proteins but I have not met it before. Can you give me some advices ?

**Comment by ZiyaoLi** [comment]
check what chain C would be in the target. there's no feature file for this chain so it's probably because of inconsistent inputs between msa searching and model inference.
