### ISSUE TITLE
questions on installing on Ubuntu Linux 22.04

### ISSUE THREAD

**Issue by avilella** [dptech-corp/Uni-Fold#134]
Hi,

I followed the installation instructions but I don't think the Uni-fold code is able to find the unicore libraries in the docker container that I downloaded. Can you clarify how to...

```
Then, you can create and attach into the docker container, and clone & install unifold.

```

Currently, not having "attached" into the docker container, I get this error:

```
LS13:~/Uni-Fold$ bash run_unifold.sh     $i     out     /data2/unifold/database     2023-10-01     model_02_ft     /home/petmedix/Uni-Fold/multimer.unifold.pt
Starting homogeneous searching...
Traceback (most recent call last):
  File "/home/petmedix/Uni-Fold/unifold/homo_search.py", line 29, in <module>
    from unifold.data.utils import compress_features
  File "/home/petmedix/Uni-Fold/unifold/__init__.py", line 5, in <module>
    from . import task, model, loss
  File "/home/petmedix/Uni-Fold/unifold/task.py", line 9, in <module>
    from unifold.dataset import UnifoldDataset, UnifoldMultimerDataset
  File "/home/petmedix/Uni-Fold/unifold/dataset.py", line 8, in <module>
    from unifold.data import utils
  File "/home/petmedix/Uni-Fold/unifold/data/utils.py", line 10, in <module>
    from . import residue_constants as rc
  File "/home/petmedix/Uni-Fold/unifold/data/residue_constants.py", line 23, in <module>
    from unicore.utils import tree_map
ModuleNotFoundError: No module named 'unicore'
Starting prediction...
Traceback (most recent call last):
  File "/home/petmedix/Uni-Fold/unifold/inference.py", line 12, in <module>
    from unifold.config import model_config
  File "/home/petmedix/Uni-Fold/unifold/__init__.py", line 5, in <module>
    from . import task, model, loss
  File "/home/petmedix/Uni-Fold/unifold/task.py", line 9, in <module>
    from unifold.dataset import UnifoldDataset, UnifoldMultimerDataset
  File "/home/petmedix/Uni-Fold/unifold/dataset.py", line 8, in <module>
    from unifold.data import utils
  File "/home/petmedix/Uni-Fold/unifold/data/utils.py", line 10, in <module>
    from . import residue_constants as rc
  File "/home/petmedix/Uni-Fold/unifold/data/residue_constants.py", line 23, in <module>
    from unicore.utils import tree_map
ModuleNotFoundError: No module named 'unicore'
```

**Comment by avilella** [comment]
I already asked this in a previous issue. Apologies.
