### ISSUE TITLE
Load Params Error

### ISSUE THREAD

**Issue by kdpan** [dptech-corp/Uni-Fold#8]
Thanks for your nice repo, but when I run the "run_from_pkl.py" file, I meet this error. What should I do?
```
Traceback (most recent call last):
  File "run_from_pkl.py", line 165, in <module>
    app.run(main)
  File "/home/panfulu/anaconda3/envs/unifold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/panfulu/anaconda3/envs/unifold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_from_pkl.py", line 106, in main
    model_params = load_params("/home/panfulu/data/alphafold/params/params_model_1.npz")
  File "/home/panfulu/project/Uni-Fold/unifold/train/utils.py", line 194, in load_params
    params = load_params_from_npz(model_path)
  File "/home/panfulu/project/Uni-Fold/unifold/train/utils.py", line 186, in load_params_from_npz
    return params['arr_0'].flat[0]
  File "/home/panfulu/anaconda3/envs/unifold/lib/python3.8/site-packages/numpy/lib/npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'arr_0 is not a file in the archive'
```

**Comment by ZiyaoLi** [comment]
Thank you for your feedback. I wonder if you are trying to load parameters from AlphaFold with Uni-Fold code? This is currently not implemented by Uni-Fold, as the format of Uni-Fold parameters is slightly different to that of AlphaFold.

**Comment by kdpan** [comment]
> Thank you for your feedback. I wonder if you are trying to load parameters from AlphaFold with Uni-Fold code? This is currently not implemented by Uni-Fold, as the format of Uni-Fold parameters is slightly different to that of AlphaFold.

那请问我在哪里可以下载unifold的参数？
Please tell me where can I download the parameters of unifold？

**Comment by ZiyaoLi** [comment]
Currently we have not released the trained parameters of Uni-Fold. The provided script is mainly for training usage. If you would like to test the performance of Uni-Fold, you may visit https://hermite.dp.tech/login and take the free trial. Thank you!
