### ISSUE TITLE
Demo Case : RuntimeError  & ChildFailedError

### ISSUE THREAD

**Issue by showlrr2** [dptech-corp/Uni-Fold#87]
The following error occurred when I ran the demo case command：
  bash train_monomer_demo.sh .

----------------------------------------

```
2022-12-23 10:48:24 | INFO | unicore_cli.train | task: AlphafoldTask
2022-12-23 10:48:24 | INFO | unicore_cli.train | model: AlphafoldModel
2022-12-23 10:48:24 | INFO | unicore_cli.train | loss: AlphafoldLoss
2022-12-23 10:48:24 | INFO | unicore_cli.train | num. model params: 94,169,845 (num. trained: 94,169,845)
2022-12-23 10:48:24 | INFO | unicore.utils | ***********************CUDA enviroments for all 1 workers***********************
2022-12-23 10:48:24 | INFO | unicore.utils | rank   0: capabilities =  7.5  ; total memory = 14.756 GB ; name = Tesla T4
2022-12-23 10:48:24 | INFO | unicore.utils | ***********************CUDA enviroments for all 1 workers***********************
2022-12-23 10:48:24 | INFO | unicore_cli.train | training on 1 devices (GPUs)
2022-12-23 10:48:24 | INFO | unicore_cli.train | batch size per device = 1
2022-12-23 10:48:24 | INFO | unicore.trainer | Preparing to load checkpoint ./checkpoint_last.pt
2022-12-23 10:48:24 | INFO | unicore.trainer | No existing checkpoint found ./checkpoint_last.pt
2022-12-23 10:48:24 | INFO | unicore.trainer | loading train data for epoch 1
2022-12-23 10:48:24 | INFO | unifold.dataset | load 2 chains (unique 1 sequences)
2022-12-23 10:48:24 | INFO | unifold.dataset | load 1 self-distillation samples.
2022-12-23 10:48:24 | INFO | unicore.tasks.unicore_task | get EpochBatchIterator for epoch 1
2022-12-23 10:48:25 | INFO | unicore.optim.adam | using FusedAdam
2022-12-23 10:48:25 | INFO | unicore.trainer | begin training epoch 1
2022-12-23 10:48:25 | INFO | unicore_cli.train | Start iterating over samples

Traceback (most recent call last):
  File "/home/unifold13/.conda/envs/unifold/bin/unicore-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/unicore_cli/train.py", line 403, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/unicore/distributed/utils.py", line 190, in call_main
    distributed_main(args.device_id, main, args, kwargs)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/unicore/distributed/utils.py", line 164, in distributed_main
    main(args, **kwargs)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/unicore_cli/train.py", line 126, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr, ckp_copy_thread)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/unicore_cli/train.py", line 216, in train
    log_output = trainer.train_step(samples)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/unicore/trainer.py", line 649, in train_step
    raise e
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/unicore/trainer.py", line 613, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/unicore/tasks/unicore_task.py", line 279, in train_step
    loss, sample_size, logging_output = loss(model, sample)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/loss.py", line 41, in forward
    out, config = model(batch)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/model.py", line 47, in forward
    outputs = self.model.forward(batch)
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/modules/alphafold.py", line 437, in forward
    ) = self.iteration_evoformer_structure_module(
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/modules/alphafold.py", line 364, in iteration_evoformer_structure_module
    m, z0, s0, msa_mask, m_1_prev_emb, z_prev_emb = self.iteration_evoformer(
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/modules/alphafold.py", line 299, in iteration_evoformer
    self.embed_templates_pair(
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/modules/alphafold.py", line 192, in embed_templates_pair
    t = self.embed_templates_pair_core(batch, z, pair_mask, tri_start_attn_mask, tri_end_attn_mask, templ_dim, multichain_mask_2d)
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/modules/alphafold.py", line 163, in embed_templates_pair_core
    single_templates = [
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/modules/alphafold.py", line 164, in <listcomp>
    self.template_pair_embedder(x, z)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/unifold13/applications/uniFold/Uni-Fold/unifold/modules/embedders.py", line 257, in forward
    x = self.linear(x.type(self.linear.weight.dtype))
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: at::cuda::blas::gemm: not implemented for N3c108BFloat16E
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 66840) of binary: /home/unifold13/.conda/envs/unifold/bin/python
Traceback (most recent call last):
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/unifold13/.conda/envs/unifold/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/unifold13/.conda/envs/unifold/bin/unicore-train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>

------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-23_10:48:29
  host      : unfold-1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 66840)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by showlrr2** [comment]
```
  (unifold) unifold13@unfold-1:/data/unifold13/applications/uniFold/Uni-Fold$ conda list
# packages in environment at /home/unifold13/.conda/envs/unifold:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   1.3.0                    pypi_0    pypi
biopython                 1.80                     pypi_0    pypi
ca-certificates           2022.10.11           h06a4308_0
certifi                   2022.12.7        py38h06a4308_0
contextlib2               21.6.0                   pypi_0    pypi
hmmer                     3.1b2                         0    biocore
kalign2                   2.04                 hec16e2b_3    bioconda
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
lmdb                      1.4.0                    pypi_0    pypi
ml-collections            0.1.1                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3
numpy                     1.24.0                   pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0
pandas                    1.5.2                    pypi_0    pypi
pip                       22.3.1           py38h06a4308_0
protobuf                  3.20.1                   pypi_0    pypi
python                    3.8.10               h12debd9_8
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.7                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0
scipy                     1.10.0rc1                pypi_0    pypi
setuptools                65.5.0           py38h06a4308_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.40.0               h5082296_0
tensorboardx              2.5.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenizers                0.13.2                   pypi_0    pypi
torch                     1.11.0                   pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
unicore                   0.0.1                    pypi_0    pypi
unifold                   2.2.1                     dev_0    <develop>
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.8                h5eee18b_0
zlib                      1.2.13               h5eee18b_0

```

**Comment by ZiyaoLi** [comment]
can you please tell me your GPU and check if it supports bfloat16? looks to me is that your device does not support bfloat16.

**Comment by ZiyaoLi** [comment]
I saw it in the log that you were using Tesla T4. It does not support bfloat16. so try to remove --bf16 and --bf16-sr in the script and check if you can run it.

**Comment by showlrr2** [comment]
> I saw it in the log that you were using Tesla T4. It does not support bfloat16. so try to remove --bf16 and --bf16-sr in the script and check if you can run it.

thanks, i'll try ~
