### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by maowayne123** [dptech-corp/Uni-Fold#90]
after i download the training dataset and start training. there is an error:
Traceback (most recent call last):
  File "/home/wayne/miniconda3/envs/unifold/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wayne/miniconda3/envs/unifold/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wayne/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/wayne/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/wayne/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/wayne/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/wayne/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/wayne/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/wayne/project/folding/uni/train.py", line 431, in <module>
    cli_main()
  File "/home/wayne/project/folding/uni/train.py", line 427, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/wayne/miniconda3/envs/unifold/lib/python3.9/site-packages/unicore-0.0.1-py3.9-linux-x86_64.egg/unicore/distributed/utils.py", line 193, in call_main
    main(args, **kwargs)
  File "/home/wayne/project/folding/uni/train.py", line 79, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/home/wayne/project/folding/uni/unifold/task.py", line 72, in load_dataset
    dataset = data_class(
  File "/home/wayne/project/folding/uni/unifold/dataset.py", line 257, in __init__
    sample_weight = load_json(
  File "/home/wayne/project/folding/uni/unifold/dataset.py", line 255, in load_json
    return json.load(open(filename, "r"))
FileNotFoundError: [Errno 2] No such file or directory: '/media/HDD/dataset/protein1/modelscope/hub/datasets/downloads/DPTech/Uni-Fold-Data/master/eval_sample_weight.json'

**Comment by guolinke** [comment]
please check your download data, it should have "eval_sample_weight.json" file.
